import { APIGatewayProxyEvent, APIGatewayProxyResult } from 'aws-lambda';
import { v4 as uuidv4 } from 'uuid';
import { successResponse, validationErrorResponse, errorResponse } from '../utils/response';
import { putItem, queryItems, getItem, batchWriteItems } from '../utils/dynamodb';

interface AutoScheduleRequest {
  locationId: string;
  startDate: string; // YYYY-MM-DD
  endDate: string; // YYYY-MM-DD
  positions: Array<{
    position: string;
    shiftsPerDay: number;
    shiftDuration: number; // hours
    startTime: string; // HH:MM
  }>;
  constraints?: {
    maxShiftsPerEmployee?: number;
    maxHoursPerEmployee?: number;
    minRestBetweenShifts?: number;
    preferredEmployees?: string[];
  };
}

/**
 * AI-Powered Auto-Scheduling Algorithm
 *
 * This function generates optimal schedules based on:
 * 1. Historical patterns (past shifts, attendance)
 * 2. Employee preferences and availability
 * 3. Skills and certifications
 * 4. Labor law compliance
 * 5. Forecasted demand
 * 6. Budget constraints
 */
export async function handler(event: APIGatewayProxyEvent): Promise<APIGatewayProxyResult> {
  try {
    const claims = event.requestContext.authorizer?.claims;
    const managerId = claims?.['custom:userId'] || claims?.sub;
    const orgId = claims?.['custom:orgId'];
    const userRole = claims?.['custom:role'];

    if (userRole !== 'MANAGER' && userRole !== 'ORG_ADMIN') {
      return validationErrorResponse('Only managers can use auto-scheduling');
    }

    const body: AutoScheduleRequest = JSON.parse(event.body || '{}');
    const { locationId, startDate, endDate, positions, constraints = {} } = body;

    if (!locationId || !startDate || !endDate || !positions || positions.length === 0) {
      return validationErrorResponse('Location, date range, and positions are required');
    }

    // Get organization compliance rules
    const org = await getItem(`ORG#${orgId}`, `ORG#${orgId}`);
    const complianceRules = org?.complianceRules || {};

    // Get location details
    const location = await getItem(`ORG#${orgId}`, `LOC#${locationId}`);
    if (!location) {
      return validationErrorResponse('Location not found');
    }

    // Get all employees for this location
    const users = await queryItems(
      'GSI1PK = :pk',
      {
        ':pk': `ORG#${orgId}#USERS`,
      },
      'GSI1'
    );

    const eligibleEmployees = users.filter((user: any) =>
      user.locationIds?.includes(locationId) && user.role === 'EMPLOYEE'
    );

    if (eligibleEmployees.length === 0) {
      return validationErrorResponse('No eligible employees found for this location');
    }

    // Get historical data for employees (last 30 days)
    const historicalShifts = await getHistoricalData(orgId, eligibleEmployees, 30);

    // Calculate employee scores based on:
    // 1. Attendance rate
    // 2. Skills match
    // 3. Availability
    // 4. Historical performance
    const employeeScores = await calculateEmployeeScores(
      eligibleEmployees,
      historicalShifts,
      positions
    );

    // Generate schedule
    const generatedShifts = await generateOptimalSchedule({
      locationId,
      startDate,
      endDate,
      positions,
      employees: employeeScores,
      complianceRules,
      constraints,
    });

    // Save generated shifts to DynamoDB
    const now = new Date().toISOString();
    const shiftsToSave = generatedShifts.map((shift: any) => ({
      PK: `LOC#${locationId}#DATE#${shift.date}`,
      SK: `SHIFT#${shift.shiftId}`,
      GSI1PK: `USER#${shift.userId}#SHIFTS`,
      GSI1SK: `DATE#${shift.date}#${shift.startTime}`,
      GSI2PK: `ORG#${orgId}#SHIFTS`,
      GSI2SK: `DATE#${shift.date}#${shift.startTime}`,
      shiftId: shift.shiftId,
      userId: shift.userId,
      locationId,
      orgId,
      date: shift.date,
      startTime: shift.startTime,
      endTime: shift.endTime,
      position: shift.position,
      status: 'SCHEDULED',
      breakRules: complianceRules.breakRules || [],
      payRate: shift.payRate,
      notes: 'Auto-generated by AI scheduler',
      createdAt: now,
      updatedAt: now,
      createdBy: managerId,
      autoScheduled: true,
      schedulingScore: shift.score,
    }));

    await batchWriteItems(shiftsToSave);

    // Generate scheduling report
    const report = generateSchedulingReport(shiftsToSave, employeeScores);

    return successResponse({
      message: 'Schedule generated successfully',
      shiftsCreated: shiftsToSave.length,
      employeesScheduled: new Set(shiftsToSave.map((s: any) => s.userId)).size,
      dateRange: { startDate, endDate },
      report,
      shifts: shiftsToSave.map((s: any) => ({
        shiftId: s.shiftId,
        userId: s.userId,
        date: s.date,
        position: s.position,
        startTime: s.startTime,
        endTime: s.endTime,
      })),
    }, 201);
  } catch (error: any) {
    console.error('Auto-schedule error:', error);
    return errorResponse(error);
  }
}

/**
 * Get historical shift data for employees
 */
async function getHistoricalData(
  orgId: string,
  employees: any[],
  days: number
): Promise<any[]> {
  const shifts: any[] = [];
  const endDate = new Date();
  const startDate = new Date();
  startDate.setDate(endDate.getDate() - days);

  for (const employee of employees) {
    const empShifts = await queryItems(
      'GSI1PK = :pk AND GSI1SK > :start',
      {
        ':pk': `USER#${employee.userId}#SHIFTS`,
        ':start': `DATE#${startDate.toISOString().split('T')[0]}`,
      },
      'GSI1'
    );
    shifts.push(...empShifts);
  }

  return shifts;
}

/**
 * Calculate employee suitability scores
 */
async function calculateEmployeeScores(
  employees: any[],
  historicalShifts: any[],
  positions: any[]
): Promise<any[]> {
  return employees.map(employee => {
    const empShifts = historicalShifts.filter(s => s.userId === employee.userId);
    const totalShifts = empShifts.length;
    const completedShifts = empShifts.filter(s => s.status === 'COMPLETED').length;
    const attendanceRate = totalShifts > 0 ? completedShifts / totalShifts : 1.0;

    // Calculate position match score
    const positionScores = positions.map(pos => {
      const hasSkill = employee.skills?.includes(pos.position.toLowerCase()) || false;
      const pastExperience = empShifts.filter(s => s.position === pos.position).length;
      return hasSkill ? 1.0 : (pastExperience > 0 ? 0.7 : 0.3);
    });

    const avgPositionScore = positionScores.reduce((a, b) => a + b, 0) / positionScores.length || 0.5;

    // Calculate availability score (assume high if no preference data)
    const availabilityScore = 1.0; // TODO: Check employee availability preferences

    // Overall score (weighted average)
    const overallScore =
      attendanceRate * 0.4 +
      avgPositionScore * 0.3 +
      availabilityScore * 0.3;

    return {
      ...employee,
      scores: {
        attendance: attendanceRate,
        positionMatch: avgPositionScore,
        availability: availabilityScore,
        overall: overallScore,
      },
      historicalShiftCount: totalShifts,
    };
  });
}

/**
 * Generate optimal schedule using greedy algorithm with constraints
 */
async function generateOptimalSchedule(params: {
  locationId: string;
  startDate: string;
  endDate: string;
  positions: any[];
  employees: any[];
  complianceRules: any;
  constraints: any;
}): Promise<any[]> {
  const { locationId, startDate, endDate, positions, employees, complianceRules, constraints } = params;

  const shifts: any[] = [];
  const start = new Date(startDate);
  const end = new Date(endDate);

  // Sort employees by overall score (descending)
  const sortedEmployees = [...employees].sort((a, b) => b.scores.overall - a.scores.overall);

  // Track employee shift counts and hours
  const employeeStats: { [key: string]: { shifts: number; hours: number; lastShiftEnd?: Date } } = {};
  employees.forEach(emp => {
    employeeStats[emp.userId] = { shifts: 0, hours: 0 };
  });

  // Generate shifts for each day
  for (let d = new Date(start); d <= end; d.setDate(d.getDate() + 1)) {
    const dateStr = d.toISOString().split('T')[0];

    // For each position requirement
    for (const posReq of positions) {
      for (let i = 0; i < posReq.shiftsPerDay; i++) {
        // Find best available employee
        let assignedEmployee = null;

        for (const emp of sortedEmployees) {
          const stats = employeeStats[emp.userId];

          // Check constraints
          if (constraints.maxShiftsPerEmployee && stats.shifts >= constraints.maxShiftsPerEmployee) {
            continue;
          }

          if (constraints.maxHoursPerEmployee && stats.hours >= constraints.maxHoursPerEmployee) {
            continue;
          }

          // Check rest time between shifts
          if (stats.lastShiftEnd && constraints.minRestBetweenShifts) {
            const shiftStart = new Date(`${dateStr}T${posReq.startTime}:00`);
            const restHours = (shiftStart.getTime() - stats.lastShiftEnd.getTime()) / (1000 * 60 * 60);
            if (restHours < constraints.minRestBetweenShifts) {
              continue;
            }
          }

          // Employee is eligible
          assignedEmployee = emp;
          break;
        }

        if (!assignedEmployee) {
          console.warn(`Could not assign employee for ${posReq.position} on ${dateStr}`);
          continue;
        }

        // Create shift
        const shiftId = uuidv4();
        const startTime = new Date(`${dateStr}T${posReq.startTime}:00`).toISOString();
        const endTime = new Date(new Date(startTime).getTime() + posReq.shiftDuration * 60 * 60 * 1000).toISOString();

        shifts.push({
          shiftId,
          userId: assignedEmployee.userId,
          date: dateStr,
          startTime,
          endTime,
          position: posReq.position,
          payRate: assignedEmployee.payRate || 15,
          score: assignedEmployee.scores.overall,
        });

        // Update stats
        employeeStats[assignedEmployee.userId].shifts += 1;
        employeeStats[assignedEmployee.userId].hours += posReq.shiftDuration;
        employeeStats[assignedEmployee.userId].lastShiftEnd = new Date(endTime);
      }
    }
  }

  return shifts;
}

/**
 * Generate scheduling report with insights
 */
function generateSchedulingReport(shifts: any[], employees: any[]): any {
  const employeeShiftCounts: { [key: string]: number } = {};
  const employeeHours: { [key: string]: number } = {};

  shifts.forEach(shift => {
    employeeShiftCounts[shift.userId] = (employeeShiftCounts[shift.userId] || 0) + 1;

    const duration = (new Date(shift.endTime).getTime() - new Date(shift.startTime).getTime()) / (1000 * 60 * 60);
    employeeHours[shift.userId] = (employeeHours[shift.userId] || 0) + duration;
  });

  const shiftDistribution = Object.entries(employeeShiftCounts).map(([userId, count]) => ({
    userId,
    shifts: count,
    hours: employeeHours[userId],
  }));

  return {
    totalShifts: shifts.length,
    employeesUsed: Object.keys(employeeShiftCounts).length,
    avgShiftsPerEmployee: shifts.length / Object.keys(employeeShiftCounts).length,
    shiftDistribution: shiftDistribution.sort((a, b) => b.shifts - a.shifts),
    coverage: {
      min: Math.min(...Object.values(employeeShiftCounts)),
      max: Math.max(...Object.values(employeeShiftCounts)),
      avg: shifts.length / Object.keys(employeeShiftCounts).length,
    },
  };
}
